### ISSUE TITLE
[Feature] Allow custom config path globally

### ISSUE THREAD

**Issue by ankitrgadiya** [rapyuta-robotics/rapyuta-io-cli#25]
The CLI currently uses the [XDG_CONFIG_PATH-based configuration file path](https://github.com/rapyuta-robotics/rapyuta-io-cli/blob/main/riocli/config/config.py#L89). For users that need multiple simultaneous configurations, its easier to define and save multiple configuration files one per account and supply the `--config` flag with the path.

Scenario 1: Sootballs wants to use our Staging environment alongside the Production. One way is to login again and again to switch the accounts but a simpler workflow is to just save the configs per environment and activate it using the `--config` flag.

Scenario 2: IO AMR uses different organization accounts per customer. For operations, it will be simpler to have one config per customer stored and then activate it using the `--config` flag.

Scenario 3: IO Developers use multiple accounts including QA and there own accounts to access the Resources in Staging environments. Again a simpler workflow is to supply the desired config file.

Additionally, users can then configure Shell Aliases for different environments having the flag as part of it.

To implement this, we need to make use of Click's context. Some work is done in the #21 PR to integrate context with login flow. We can make use of the context in every sub-command so initialization of Configuration only happens at the global level at which point we can pass the `--config` argument.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=894412921)

**Comment by pallabpain** [comment]
Tracked in Wrike
